### PR TITLE
Allow additional externals to be included

### PR DESCRIPTION
**Pull request by jprosevear**
Fix for #42

### CODE REVIEW

**Review by crutchcorn — APPROVED** [review]
Approved! LGTM, thanks!

**Comment by crutchcorn** [comment]
Err... We have some problems here with our Prettier config. Tagging in the big guns (@lachlancollins) to review

> Lachlan, I'm running into issues where prettier is formatting every file despite looking good in CI/CD otherwise - on my Windows Machine

**Comment by jprosevear** [comment]
Fixed formatting, looking at the build issue

**Comment by jprosevear** [comment]
@crutchcorn @lachlancollins resolved, pnpm test:pr now passes locally

**Review by lachlancollins — APPROVED** [review]
LGTM!

**Pull request merged**
